obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-gpiomux.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-keypad.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-mmc.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-storage.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-wifi.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-regulator.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-pmic.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-audio.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-rfkill.o
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-display.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_DOUBLESHOT) += board-doubleshot-camera.o
endif
